version: '2.1'
orbs:
  node: circleci/node@5.0.0
jobs:
  test:
    docker:
      - image: 'cimg/node:17.4.0'
    steps:
      - checkout
      - run: npm i
      - run: npm run test
      
  integrateFrontend:
    docker:
      - image: 'cimg/node:17.4.0'
    steps:
      - run: git clone https://github.com/ValerianHarasse/3w5-h22-tp2-backend.git
      - run: git clone https://github.com/ValerianHarasse/3w5-h22-tp2-frontend.git
      - run: cd 3w5-h22-tp2-frontend && npm i 
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - 3w5-h22-tp2-backend-test1
      - run: cd 3w5-h22-tp2-backend && mkdir public
      - run: cp -rT ./3w5-h22-tp2-frontend/build ./3w5-h22-tp2-backend/public
      
workflows:
  test_my_app:
    jobs:
      - test
       - integrateFrontend:
           requires:
           - test
